### ISSUE TITLE
MultiFields 的使用

### ISSUE THREAD

**Issue by FantasyJony** [chexiongsheng/XUUI#3]
MultiFields 之前是用于什么功能的 翻项目里面 貌似没对这个字段的支持啊

**Comment by chexiongsheng** [comment]
当时希望多字段的绑定，bindTo设置类似这样{text = a.b.c, img = a.b.d}，然后lua的a.b.c会同步到c#对象的text字段，a.b.d同步到img

**Comment by FantasyJony** [comment]
我现在有个需求是image 需要两个DataConsumer参数： 一个DataConsumer < Texture2D >  来设置sprite ；一个DataConsumer < bool >  来置灰，这个MultiFields字段是否就是类似这种运用场景？

再者我希望image在异步加载图片的时候把scale = Vector.zero ；异步完毕再scale = Vector.one，来防止图片闪白；突然间一个image需要3个控制量了...

这种多字段控制多内容的如何实现？

===================================================

突然想到一个可行的方法是 实现多个image的Adaper，如：ImageGray 控制置灰，ImageLoad控制加载的scale值，但是这种方式必然造成一个组件多个MonoBehaviour...
然而这种方式似乎跟ViewBinding无法组合起来...

**Comment by angyangjiong** [comment]
我现在有个需求是image 需要两个DataConsumer参数： 一个DataConsumer<Texture2D> 来设置sprite ；一个DataConsumer<bool> 来置灰，这个MultiFields字段是否就是类似这种运用场景？
这种多字段控制多内容的如何实现？

**Comment by ghost** [comment]
> 我现在有个需求是image 需要两个DataConsumer参数： 一个DataConsumer < Texture2D > 来设置sprite ；一个DataConsumer < bool > 来置灰，这个MultiFields字段是否就是类似这种运用场景？
> 
> 再者我希望image在异步加载图片的时候把scale = Vector.zero ；异步完毕再scale = Vector.one，来防止图片闪白；突然间一个image需要3个控制量了...
> 
> 这种多字段控制多内容的如何实现？
> 
> ===================================================
> 
> 突然想到一个可行的方法是 实现多个image的Adaper，如：ImageGray 控制置灰，ImageLoad控制加载的scale值，但是这种方式必然造成一个组件多个MonoBehaviour... 然而这种方式似乎跟ViewBinding无法组合起来...

问下最后怎么实现这种需求的？
